### ISSUE TITLE
Add a site-visit counter

### ISSUE THREAD

**Issue by actuallyaryaman** [Doofenshmirtz-Evil-Incorp/Fuelish#20]
Want to add a site visit counter that goes well with the design aesthetics of the website.

**Comment by krishprav** [comment]
@actuallyaryaman  Added Feature :site-visit counter https://github.com/Doofenshmirtz-Evil-Incorp/Fuelish/issues/20  
![image](https://github.com/Doofenshmirtz-Evil-Incorp/Fuelish/assets/118839797/e5dad0f7-1528-4c98-b988-491b37804b12)

**Comment by krishprav** [comment]
https://krishprav.github.io/Fuelish/

**Comment by actuallyaryaman** [comment]
Hi @krishprav kindly, check your css in a mobile device as well and change the style of the counter in the dark mode to make it go better with the website

**Comment by actuallyaryaman** [comment]
#26 added site hit counter.
