### ISSUE TITLE
Add responsive elements and animations

### ISSUE THREAD

**Issue by actuallyaryaman** [Doofenshmirtz-Evil-Incorp/Fuelish#21]

**Comment by Ahnaf-codes** [comment]
hey @actuallyaryaman i'd like to work on this please assign me

**Comment by Niraj-1729** [comment]
Hey !! assign this to me, I can work on this .

**Comment by Niraj-1729** [comment]
I am waiting for you response

**Comment by vikki9121** [comment]
@actuallyaryaman  hey assign me this task

**Comment by actuallyaryaman** [comment]
@vikki9121 https://github.com/Doofenshmirtz-Evil-Incorp/Fuelish/issues/51

**Comment by Asvin1** [comment]
#34 same thing
