### ISSUE TITLE
Fix desktop view alignment and button colours

### ISSUE THREAD

**Issue by actuallyaryaman** [Doofenshmirtz-Evil-Incorp/Fuelish#23]
The desktop view has messed up alignment of the container and made the container transparent which needs to be fixed.

**Comment by actuallyaryaman** [comment]
Sure. If you want I can assign you to this.
Kindly go through the codebase and see our mobile view to better understand our design, and read contributing.md
Don't forget to star the repo! ✨

**Comment by satvik225** [comment]
I went through the codebase of this repo and I am can take this issue. Please assign this to me.

**Comment by actuallyaryaman** [comment]
@dipenpatel1901  The footer should be in the bottom centre.
And try and make the transparency go away to so that we can have a better idea of whether to change the container location.

**Comment by dipenpatel1901** [comment]
Ok @actuallyaryaman will fork and make the changes and send u a PR by tomorrow

**Comment by dipenpatel1901** [comment]
i have completed the changes @actuallyaryaman

**Comment by actuallyaryaman** [comment]
#33
