### ISSUE TITLE
Adding Light and Dark mode

### ISSUE THREAD

**Issue by Riddhick** [Doofenshmirtz-Evil-Incorp/Fuelish#24]
Hi , can I work on providing a Light theme for the website ?

**Comment by actuallyaryaman** [comment]
@Riddhick Sure. Kindly go through the codebase and contributing.md. 
And try and make the light mode consistent with the dark mode color theme.
Let me know and I'll assign the issue to you 

And don't forget to star our repo ⭐✨

**Comment by actuallyaryaman** [comment]
@krn1904 the issue is open, you're free to explore and try out.
If you do have something create a PR and we'll review it and see to it if it's mergeable.

Kindly star our repo while you are at it ⭐✨

**Comment by Riddhick** [comment]
Okay I am working on it.

**Comment by Raghu1124** [comment]
@actuallyaryaman can you allow mw to work on this issue.

**Comment by actuallyaryaman** [comment]
@Raghu1124 buddy it's an open-source project.
You don't need to ask me before contributing.. 
Simply go through the codebase, [Contributin.md](https://github.com/Doofenshmirtz-Evil-Incorp/Fuelish#contributing), and if the changes you made works well with our project we will surely accept it.

Don't forget to star the repo while you are at it. ⭐ ✨
