### ISSUE TITLE
Adding login page

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [Doofenshmirtz-Evil-Incorp/Fuelish#28]
@actuallyaryaman Hi , can I work on providing login page for the website ?

**Comment by actuallyaryaman** [comment]
this is a utility app which does not require user login.
you are free to contribute through other issues.
And don't forget to star out repo! thank you!

**Comment by ARCHITABHATTAD** [comment]
@actuallyaryaman can I create a issue to include a feedback form or survey to gather user opinions and suggestions for further improvements?
