### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by YashaKirad** [Doofenshmirtz-Evil-Incorp/Fuelish#45]
I would like to change the UI Design for ease of use like widening the black container for more map coverage.
Please assign it to me

**Comment by actuallyaryaman** [comment]
You are free to make a pr and if it suits the design-philosophy we'll definitely merge it.

While you are at it, don't forget to star our repo. ⭐ ✨

**Comment by Nupur19nj** [comment]
can you please assign me this task under hacktober-accepted!

**Comment by actuallyaryaman** [comment]
The repository is already under hactoberfest. There is no need for assignment.
Simply create a PR under the hacktoberfest-accepted label.

**Comment by Nupur19nj** [comment]
ya but can you assign me this task like till now it's not assigned to anyone!

**Comment by actuallyaryaman** [comment]
@Nupur19nj #51
