### ISSUE TITLE
BUG: whatsapp logo is not visible in light mode and the curser is not pointer

### ISSUE THREAD

**Issue by shivasaikiran** [Doofenshmirtz-Evil-Incorp/Fuelish#49]
BUG: whatsapp logo is not visible in light mode and the curser is not pointer 

can you assign this issue to me behalf of hacktoberfesr

**Comment by actuallyaryaman** [comment]
**Important**: Please do not ask for assignment before creating a pull request. We encourage you to directly create a pull request for your contributions.
Thank you!❤️
