### ISSUE TITLE
Separate css files

### ISSUE THREAD

**Issue by actuallyaryaman** [Doofenshmirtz-Evil-Incorp/Fuelish#54]
create two separate css files namely dark.css and light.css based on the dark and light mode, to increase code readability and reducing clutter in a single file, whilst updating javascript to function accordingly

**Comment by 08Uzair** [comment]
Please Assign this to me

**Comment by actuallyaryaman** [comment]
#51

**Comment by actuallyaryaman** [comment]
> Please Assign this to me 

#51

**Comment by actuallyaryaman** [comment]
@08Uzair #51

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by actuallyaryaman** [comment]
#57
