### ISSUE TITLE
Bug: Changing the settings icon to the light mode icon for better UI

### ISSUE THREAD

**Issue by Namesh2710** [Doofenshmirtz-Evil-Incorp/Fuelish#60]
https://github.com/Doofenshmirtz-Evil-Incorp/Fuelish/assets/121512046/f299723b-fd49-4e02-8c8d-40470a7590b6

**Comment by Namesh2710** [comment]
hii , please assign this issue to me.

**Comment by actuallyaryaman** [comment]
light mode is removed for the upcoming versions.
